version: '3.8'

services:
  app:
    image: warehouse
    ports:
      - 5005:80
    environment:
      - ConnectionStrings__Redis=db:6379
      - ConnectionStrings__RabbitMq=rabbitmq-stream://guest:guest@rabbitmq:5552/%2f
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OPENTELEMETRY_OLTP_EXPORTER_ENABLED=true
      - OPENTELEMETRY_ENABLED=true
      - OPENTELEMETRY_LOGGING_ENABLED=true
    depends_on:
      - "db"
      - "rabbitmq"
  db:
    image: redis:6-bullseye
    restart: unless-stopped
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
      - 5552:5552
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411

  otel-collector:
    image: otel/opentelemetry-collector:0.54.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "9411"   # Zipkin receiver
      - "55679:55679" # zpages extension
      - "4317:4317"
    depends_on:
      - jaeger
      - zipkin
