receivers:
  otlp:
    protocols:
      grpc:
  zipkin:

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  file:
    path: /etc/output/logs.json
    
processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp, zipkin]
      exporters: [zipkin, jaeger, logging]
      processors: [batch]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [logging, file]